- requirements/index.html
Based on the [original TF draft as of today](https://docs.google.com/document/d/15F4KuNXYK5q2rOgb4ktHiJQMQpAEL9EetARpMU3vD_A/)
* Added text about what this  is and plans for it. 
* Removed things that were stated twice
* Simplified some sentences
* Removed the Abstract (!)
* Split principles into process and results
(there's more to do here)
> put rough draft in github

- prototypes/ConformancePrototype.html
First draft of the Conformance Prototype based on AccessU and Design Sprint feedback.
> add first draft of Conformance Prototype

- requirements/index.html
This version cleans up the prior version with incorrect or missing REspec code.  It adds the participants and cleaned up some grammar problems identified in the 5 June Silver meeting.
> Created a new version from REspec template with Silver Requirements text

- requirements/index.html
Removed the commented out sections in changelog
Removed first line (which appeared to come from the template, I will go back and look at that)
Added paragraph to SOTD
> Changes requested in review by mcooper

- prototypes/FlavorPrototype/aria.html
- prototypes/FlavorPrototype/assets/css/components.css
- prototypes/FlavorPrototype/assets/css/flavor-colors.css
- prototypes/FlavorPrototype/assets/css/master.css
- prototypes/FlavorPrototype/componentExamples.html
- prototypes/FlavorPrototype/index.html
- prototypes/FlavorPrototype/pdf.html
- prototypes/FlavorPrototype/readme.md
- prototypes/FlavorPrototype/silverlight.html
- prototypes/FlavorPrototype/staticWeb.html
- prototypes/index.html
- prototypes/readme.md
Prototype to show the possibility of including different 'Flavours' of Silver to demonstrate guidance to individual technologies. Takes WGAC 2.0 SC 1.1.1 (Non-Visual Text) as an example for content:
Raw Git Example is here:
[https://rawgit.com/w3c/silver/mc-flavor-prototype/prototypes/FlavorPrototype/index.html](https://rawgit.com/w3c/silver/mc-flavor-prototype/prototypes/FlavorPrototype/index.html
)
> Mc Flavour Prototype

- assets/css/main.css
- index.html
- prototypes/index.html
Reflow fixes to main pages of site.
> Fixes to home page to improve readability

- index.html
> Updated main index page with links to Silver resources outside GH

- prototypes/index.html
> Adding links to Plain language and IA proposal

- index.html
- prototypes/index.html
- requirements/index.html
Added paragraph to Technology Neutral Requirement
> Requirements updates

- prototypes/PlainLanguage/index.html
added explanation, context for evaluation and links to comments.
> Index Plain Language Prototype

- prototypes/ConformancePrototype/index.html
added a placeholder for comments in the Abstract and a placeholder in Individual for an example.
> Conformance minor changes

- prototypes/PlainLanguage/index.html
- prototypes/PlainLanguage/site/index.html
and changed /site/index for plain language from Flavors text
> add link to the survey

- prototypes/FlavorPrototype/site/index.html
and changed /site/index for survey and link to Github issue with a prefilled title
> added link to survey

- prototypes/index.html
> added external prototype links to index

- prototypes/index.html
... and directed people toward the Google doc with the most recent plain language prototype information.
> marked plain language flavor prototype out of date

- prototypes/PlainLanguage2/SectionHeading.html
- prototypes/PlainLanguage2/index.html
- prototypes/PlainLanguage2/style.css
- prototypes/PlainLanguage2/template.html
and heading changes tobetter align with IA plan.  Explaination of the samples.
> Cosmetic Updates

- prototypes/EdDraftPrototype/index.html
Fixing the heading levels correct in ReSpec.
> ED draft - Respec fixes and minor language changes

- edDraft/index.html
- edDraft/respec-config.js
A prototype of a TR document with some of the Conformance work
> early draft

- edDraft/index.html
- requirements/index.html
Changes from the AGWG-Silver F2F meeting at CSUN March 11, 2019
> Update from CSUN F2F and AGWG survey

- prototypes/PlainLanguage2/SectionHeading.html
- requirements/index.html
Updates Introduction and SOTD to add section on the difference between Design Principles and Requirements.  Added explanation of phase of Requirements to the SOTD.
> Requirements update js

- requirements/index.html
based on CSUN feedback, survey, and discussions from Silver meetings of March 22 & 26.
> updates to requirements

- requirements/index.html
New Scope section in Intro
Changing the title to Multiple Ways to Present
> updates from Silver meeting of 26 April

- requirements/index.html
edits from JB on Scope
Revised Technology Neutral
Consensus on Data Driven to date.
Updated changelog
> update Requirements 30 April

- guidelines/index.html
- index.html
and minor updates to Guidelines Introduction
> links to Guidelines and Explainer

- guidelines/explainer.html
- guidelines/index.html
- prototypes/PlainLanguage2/ClearWords.html
- prototypes/PlainLanguage2/index.html
plus updates to introduction, demo of some new content, updated list of participants
> Ed draft js oct - updates from meetings

- guidelines/index.html
- prototypes/PlainLanguage2/style.css
- prototypes/PlainLanguage2/visualContrast.html
- prototypes/PlainLanguage2/warning.css
IN the main document and in the tabbed Explainer
> Added draft of Visual Contrast

- prototypes/PlainLanguage2/ClearWords.html
Based on 13 January subgroup meeting
> added Plan tab for Clear Words

- guidelines/explainers/ClearWords.html
- guidelines/explainers/SectionHeading.html
- guidelines/explainers/index.html
- guidelines/explainers/magicsauce.js
- guidelines/explainers/readme.md
- guidelines/explainers/style.css
- guidelines/explainers/template.html
- guidelines/explainers/visualContrast.html
- guidelines/explainers/warning.css
- guidelines/index.html
- guidelines/methods/Method-plain-language-principles.html
update links
Added Test tab to Method for Clear Words
> Move Explainers into a new folder

- guidelines/explainers/visualContrast.html
> Updates to Get Started tab

- index.html
- subgroups/xr/captioning/index.html
- subgroups/xr/captioning/user-requirements.html
- subgroups/xr/index.html
- subgroups/xr/minutes.html
Added in basic XR section of github pages site with information on tasks carried out so far.
> New XR section of site

- subgroups/xr/captioning/what-is-captioning.html
Many sources within W3C have devloped their own definition of captions. These include, but are not limited to:
*   The [Web Accessibility Initiative](https://www.w3.org/WAI/media/av/captions/) defining captions as _a text version of the speech and non-speech audio information needed to understand the content. They are displayed within the media player and are synchronized with the audio._.
*   [Media Accessibility User Requirements](https://www.w3.org/TR/media-accessibility-reqs/#captioning) defining captions as being _for people who are deaf or hard-of-hearing, captioning is a prime alternative representation of audio_.
*   [Web Content Accessibility Guidelines (2.1)](https://www.w3.org/TR/WCAG21/#dfn-captions) defines captions as _synchronized visual and/or text alternative for both …
> Initial captioning definition - XR Subgroup

- subgroups/xr/captioning/index.html
- subgroups/xr/captioning/user-requirements.html
- subgroups/xr/captioning/what-is-captioning.html
- subgroups/xr/captioning/xr-captioning-user-needs.html
- subgroups/xr/index.html
- subgroups/xr/minutes.html
This document presents the accessibility requirements for users when using captions and audio descriptions within a web based mixed reality environment.
It provides an introduction to the needs of users in relation to XR Captioned content using Functional Needs provided in Section 4.2 of [EN301-549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf). We anticipate that this will be updated by a functional needs list created by the _Silver Functional Needs Sub-Group_ at a later date.
The User Needs that are outlined were constructed by taking two approaches:
1.  A **Top-Down** approach was used where existing user needs identified in [XR Accessibility User Requirements](https://www.w3.org/TR/xaur/) were analysed and relevance determined
2.  A …
> XR Captions - Initial User Needs Draft

- subgroups/xr/captioning/functional-outcomes.html
Changes in Functional Outcome text. Taken from
https://www.w3.org/2020/08/03-silver-minutes.html
> Changes to Functional Outcome Text

- guidelines/index.html
Please review and merge if agreed
> Edits from AG meeting and capitalization fixes

- guidelines/index.html
I saw there were still links to the Google docs from the master.  Do you want me to remove them so you don't have to run a script to do that?
> Filled in Outcome names from the Outcome result

- methods/template/description.html
- methods/template/examples.html
- methods/template/index.html
- methods/template/intro.html
- methods/template/resources.html
- methods/template/scoring.html
- methods/template/tests.html
I added code to each template to speed things up for me.  I didn't change anything substantive, and labeled each commit.  You can throw it away if you want.  I will use my local copy.  I think it will make it easier for the people who will be coding these, but I don't really care.
> Js method templates

- guidelines/explainers/ClearWords.html
- guidelines/index.html
- how-tos/clear-words/design.html
- how-tos/clear-words/develop.html
- how-tos/clear-words/examples.html
- how-tos/clear-words/get-started.html
- how-tos/clear-words/index.html
- how-tos/clear-words/outcomes.html
- how-tos/clear-words/plan.html
- how-tos/clear-words/resources.html
with the last commit being an update to the phrasing of one Outcome in the guidelines.  It explains more what "diacritical" refers to.
> Js clear words how to

- methods/alt-text-editable/description.html
- methods/alt-text-editable/examples.html
- methods/alt-text-editable/index.html
- methods/alt-text-editable/intro.html
- methods/alt-text-editable/resources.html
- methods/alt-text-editable/scoring.html
- methods/alt-text-editable/tests.html
Text Alternatives method from ATAG.
> Method   alternative content editable

- guidelines/index.html
- methods/alt-text-editable/scoring.html
- methods/clear-words/scoring.html
- methods/decorative-images/scoring.html
- methods/font-characteristics-contrast/scoring.html
- methods/functional-images/scoring.html
- methods/headings-in-html/scoring.html
- methods/headings-in-html/tests.html
- methods/images-of-text/scoring.html
- methods/informative-images/scoring.html
- methods/relevant-headings/description.html
- methods/relevant-headings/scoring.html
- methods/relevant-headings/tests.html
- methods/template/scoring.html
- methods/visually-distinct/scoring.html
- methods/xr-audio-metadata/scoring.html
- methods/xr-caption-reflow/scoring.html
- methods/xr-text-equiv/scoring.html
Needs review. The method titles need to be updated to match the revised ones in the main document
> Updated the scoring tabs on all methods; Fixed methods under structure

- functional-needs/index.html
- guidelines/index.html
- guidelines/respec-config.js
Preview at https://raw.githack.com/w3c/silver/minor-cleanup/guidelines/index.html
> Minor cleanup

- guidelines/index.html
As promised in the AGWG call yesterday.
> Suggest conforming alternative version

- methods/font-characteristics-contrast/apca.css
- methods/font-characteristics-contrast/description.html
- methods/font-characteristics-contrast/intro.html
- methods/font-characteristics-contrast/resources.html
- methods/font-characteristics-contrast/tests.html
Hi Michael, here are my proposed changes. I tried to emulate much of the tone and brevity of the methods for the various alt-text entries. They are all separate commits  but did you mean a separate pull request for each? 
**Change Summary:**
**Intro:** Added a brief paragraph, and also edited the platform and technology to be similar to the other methods.
**Description**: Added a brief four paragraph description, just 202 words, similar or less than the other methods.
**Tests**: Clarified some issues and procedures. Updated the table, it's much shorter now, and includes some of the more recent values. The APCA.css file for the table is in this directory.
**Resources**: Added two additional external resources, including the GitHub repo for APCA code, and an explanatory line next to each …
> Myndex patch 1

- guidelines/index.html
Copy update for the [Gold conformance level](https://w3c.github.io/silver/guidelines/#gold)
> [fix] Update bronze -> silver for Gold conformance level

- w3c.json
s/note-track/note per https://w3c.github.io/w3c.json.html
> Align repo-type with documented taxonomy

- methods/errors-instructions-source/examples.html
> Fix examples

- guidelines/index.html
- how-tos/clear-words/design.html
- how-tos/clear-words/develop.html
- how-tos/clear-words/get-started.html
Changes in to Clear Words How To in response to #222 and #264.
> Clear language comments js apr2021

- requirements/index.html
Update based on request from COGA.
> Requirements wording update

- guidelines/guidelines.css
- guidelines/guidelines.js
Remove role=region on details
Change table summary to caption
> Pass HTML validator

- explainer/index.html
Updated explainer from the 8 June AGWG meeting.  Added 2 Conformance goal, 1 Inclusion goal and put and ednote on Accessibility Supported goal to say it does not have consensus.
> Explainer edits js

- methods/errors-instructions-source/examples.html
showing the code example in error sub group method doc
[preview](https://rawcdn.githack.com/w3c/silver/af24c6ed5148521c7cddf943fc65de1b353cace4/methods/errors-instructions-source/examples.html)
> added code tag to show coding example

- use-cases/index.html
- use-cases/use-cases-breakdown.html
THis PR removes sections of the use cases that are controversial and would be a distraction.   The sections have been copied to another file renamed use-cases-breakdown.html
> Use cases jun 22

- guidelines/wcag3.js
This fixes an error that causes the filter script to stop running
> fix missing function call

- requirements/index.html
added new design principal for do no harm.
> updated principal

- guidelines/index.html
Completed work from the Test Types & Terminology subgroup.
> Test Types & Terminology update

- methods/functional-images/tests.html
- methods/text-equiv/tests.html
- requirements/index.html
Initial PR for the Issue Severity subgroup. Added content to describe our work to date and also what needs to happen next. Also added examples of critical failures to functional images and text equivalent outcomes.
> Issue severity subgroup pre-TPAC content

- guidelines/guidelines.css
- guidelines/guidelines.js
Updates output of the script to match redesign request
[Preview](https://raw.githack.com/w3c/silver/script-updates-may-2023/guidelines/index.html)
> Script updates may 2023

- guidelines/index.html
These are Jeanne's To Do items from the list of editorial work. It includes the plain language summaries adjusted for the new placement of content sections.  Jeanne also edited the Introduction to reduce repetition and improve clarity.
> Plain language june 2023 js

- guidelines/guidelines.css
- guidelines/index.html
> CSS Updates

- acknowledgements/ag-wg-active.html
- acknowledgements/archive/ag-wg-active-2020.html
- acknowledgements/archive/funders-2020.html
- acknowledgements/archive/key-contributors-2021.html
- acknowledgements/archive/research-partners-2020.html
- acknowledgements/archive/silver-active-2020.html
- acknowledgements/funders.html
- acknowledgements/key-contributors.html
- acknowledgements/silver-active.html
- guidelines/index.html
I still don't have all the headings appearing properly in ToC, but it can be previewed for pre-CFC.
> Acknowledgements q2 23

- guidelines/index.html
Respec pesters about this and it will eventually be required, so plopping in a placeholder security and privacy section.
> privacy and security considerations

- guidelines/index.html
- guidelines/respec-config.js
Switch comment and review location to the wcag3 repo
> Comment update

- requirements/index.html
> Technology scope update

- requirements/index.html
> Update "Multiple ways to display" section

- requirements/index.html
A few issues had agreed resolutions without PRs, this is to catch those up and close the issues.
Resolving issue 307 (minutes 27th Feb)
Closes #307
> Catchup PR

- requirements/index.html
Closes [Issue 44](https://github.com/w3c/wcag3/issues/44) in WCAG3 repo
Closes #727
All the updates are from comments in [Issue 44](https://github.com/w3c/wcag3/issues/44).
Preview in context from this [HTML Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fsilver%2Fmain%2Frequirements%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fsilver%2FIssue44-Testable%2Frequirements%2Findex.html#design_principles).
> Update from Issue 44
